import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service | Zylos",
  description: "Terms of Service for Zylos AI services",
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-4 py-12 max-w-3xl">
        <Link
          href="/"
          className="inline-flex items-center text-muted-foreground hover:text-primary transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>

        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">Last updated: January 13, 2026</p>

        <div className="prose prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Zylos services, you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Zylos is a personal AI assistant that helps with various tasks including email management,
              scheduling, research, and automation. The service is provided on an &quot;as is&quot; basis
              and is primarily intended for personal use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">3. User Responsibilities</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              As a user, you agree to:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
              <li>Provide accurate information when authorizing service connections</li>
              <li>Use the service in compliance with applicable laws</li>
              <li>Not attempt to abuse, hack, or disrupt the service</li>
              <li>Maintain the security of your account credentials</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">4. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Zylos name, logo, and associated materials are the property of their respective owners.
              Content generated by the AI assistant is provided for your personal use.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">5. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              Zylos is provided &quot;as is&quot; without warranties of any kind. We are not liable for
              any damages arising from the use of our services, including but not limited to
              direct, indirect, incidental, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">6. Third-Party Services</h2>
            <p className="text-muted-foreground leading-relaxed">
              Zylos integrates with third-party services such as Google APIs. Your use of these
              integrations is subject to the respective third-party terms of service.
              We are not responsible for third-party service availability or changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">7. Modifications</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify these terms at any time. Continued use of the service
              after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">8. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              You may stop using Zylos services at any time by revoking access through your
              connected accounts. We reserve the right to terminate or suspend access to our
              services at our discretion.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-primary mb-4">9. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              For questions about these Terms of Service, please contact us through our
              Twitter account{" "}
              <a
                href="https://twitter.com/AiZylos"
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline"
              >
                @AiZylos
              </a>.
            </p>
          </section>
        </div>

        <footer className="mt-16 pt-8 border-t border-white/5 text-center text-muted-foreground text-sm">
          <p>© 2026 Zylos AI</p>
        </footer>
      </div>
    </main>
  );
}
